In [1]:
import numpy as np

In [ ]:
# numpy array operations

In [2]:
# Create the 1D NumPy array for Week 1 temperatures
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [3]:
array_shape = temperatures_w1.shape

array_dtype = temperatures_w1.dtype

array_size = temperatures_w1.size



print(f"Array Shape: {array_shape}")
print(f"Data Type: {array_dtype}")
print(f"Number of Elements: {array_size}")


Array Shape: (7,)
Data Type: float64
Number of Elements: 7


In [4]:
# Convert the array to Fahrenheit
temperatures_w1_f = (temperatures_w1 * 9/5) + 32

print(temperatures_w1_f)

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [5]:
# Calculate statistics for Celsius
max_c = temperatures_w1.max()
min_c = temperatures_w1.min()
mean_c = temperatures_w1.mean()


print(f"Celsius    -> Max: {max_c}°C | Min: {min_c}°C | Mean: {mean_c:.2f}°C")


Celsius    -> Max: 26.1°C | Min: 20.8°C | Mean: 23.54°C


In [ ]:
#Array Slicing and Indexing:

In [8]:
# Slice the first three elements 
first_three_days = temperatures_w1[:3]

# Slice the last two elements
weekend_temps = temperatures_w1[-2:]

# Slice the middle three elements
middle_three_days = temperatures_w1[2:5]



print(first_three_days)
print(weekend_temps)
print(middle_three_days)


[22.5 25.3 20.8]
[24.8 21.9]
[20.8 23.4 26.1]


In [ ]:
#Create a 2D Array:

In [9]:
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],  
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]   
])


print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [ ]:
#Inspect and Slice the 2D Array:

In [10]:
print(f"Array Shape: {temperatures.shape}")
print(f"Data Type: {temperatures.dtype}")
print(f"Total Number of Elements: {temperatures.size}")

Array Shape: (2, 7)
Data Type: float64
Total Number of Elements: 14


In [11]:
# 1. Extract the temperatures for each week individually
week1_temps = temperatures[0, :]
week2_temps = temperatures[1, :]

# 2. Extract the weekends (last two days) for both weeks simultaneously
# ':' selects all rows (both weeks), and '-2:' selects the last two columns
both_weekends = temperatures[:, -2:]

# Print the results
print("Week 1 Temperatures:", week1_temps)
print("Week 2 Temperatures:", week2_temps)
print("Weekend Temperatures (Both Weeks):\n", both_weekends)

Week 1 Temperatures: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2 Temperatures: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Weekend Temperatures (Both Weeks):
 [[24.8 21.9]
 [22.8 20.1]]


In [ ]:
#Pandas Series:

In [ ]:
#Creating Pandas Series:

In [12]:
import pandas as pd

marks_data = [95, 92, 89, 85, 80]
ranks_index = ['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']

marks = pd.Series(data=marks_data, index=ranks_index)

print(marks)


Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [ ]:
#Indexing and Slicing:

In [13]:
first_rank_mark = marks.iloc[0]

print(f"The mark of the 1st rank student is: {first_rank_mark}")

The mark of the 1st rank student is: 95


In [14]:
top_three_marks = marks.loc[['Rank1', 'Rank2', 'Rank3']]

print(top_three_marks)

Rank1    95
Rank2    92
Rank3    89
dtype: int64


In [15]:
third_rank_mark = marks.iloc[2]

print(f"The mark of the 3rd rank student is: {third_rank_mark}")

The mark of the 3rd rank student is: 89


In [16]:
# Create and apply the boolean mask
high_ranks = marks[marks > 90]

print(high_ranks)

Rank1    95
Rank2    92
dtype: int64


In [ ]:
#3. Manipulating Series:

In [18]:
marks.loc['Rank1'] = 100
# Drop the last rank from the Series
marks = marks.drop('Rank5')

print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


In [19]:
cgpa = marks / 10

print(cgpa)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [ ]:
#Pandas DataFrame:

#1. Creating Pandas DataFrame:

In [20]:
# Create the transactions DataFrame
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 
                        'Clothing', 'Electronics', 'Furniture', 'Clothing', 
                        'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 
               'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [ ]:
#Data Exploration:

In [21]:
print(transactions.head())
print(transactions.tail())
print("Shape:", transactions.shape)
print(f"Column Names: {list(transactions.columns)}")
print(transactions.dtypes)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
Shape: (10, 4)
Column Names: ['TransactionID', 'ProductCategory', 'Region', 'Amount']
TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object


In [22]:
# Select and display specific columns
product_amounts = transactions[['ProductCategory', 'Amount']]

print(product_amounts)

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [23]:
last_three_cols = transactions.iloc[:, -3:]

print(last_three_cols)

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [24]:
# Filter rows where Region is 'North' AND Amount is greater than 200
filtered_df = transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]

print(filtered_df)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [25]:
# Get the value counts for the ProductCategory column
category_counts = transactions['ProductCategory'].value_counts()

print(category_counts)

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [26]:
# Find the unique values in the Region column
unique_regions = transactions['Region'].unique()

print(unique_regions)

['North' 'South' 'East' 'West']


In [27]:

# Group by Region and calculate the mean of the Amount column
region_means = transactions.groupby('Region')['Amount'].mean()

print(region_means)

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [ ]:
#3. Manipulating the DataFrame:

In [28]:
# Update Amount for TransactionID 102
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

print(transactions.head())

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200


In [29]:
# Add the 'Discount' column (10% of Amount)
transactions['Discount'] = transactions['Amount'] * 0.10

print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


In [30]:
# Remove the row where TransactionID is 109
transactions = transactions[transactions['TransactionID'] != 109]

print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [31]:
# Drop the 'Discount' column
transactions = transactions.drop('Discount', axis=1)

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
